import type { Metadata } from "next";
import {Lexend } from "next/font/google";
import Header from "@/(components)/Header";
import Sidebar from "@/(components)/Sidebar";
import Createnotes from "@/(components)/Createnotes";
import ContextWrap from "@/(components)/contextWrapper";
import "./globals.css";



const lexendFont = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lexendFont.variable} font-lexend h-full antialiased`}
    >
     
     <ContextWrap>

     <Sidebar ></Sidebar>
     
     {children}

     </ContextWrap>
    
    
    </html>
  );
}
